//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.VaccinationDate = new HashSet<VaccinationDate>();
        }
        public string Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Phone { get; set; }
        public string Mobile_Phone { get; set; }
        public Nullable<System.DateTime> PositiveResultDate { get; set; }
        public Nullable<System.DateTime> CureDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaccinationDate> VaccinationDate { get; set; }
    }
}
